name: Update ZH/JA Docs

on:
  workflow_dispatch:              # 手動鈕
  # schedule:
  #   - cron: '0 3 * * *'         # 之後想定時再打開

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch translation sheet
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1juP5Sy3VnptGwzq9eKGid55iGo-wB7r_Fs4cqjvyFZE/export?format=csv" -o translations.csv

      - name: Build markdown
        run: |
          python scripts/csv2md.py translations.csv docs

      - name: Commit back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(i18n): update ZH & JA"
